"""
Domain models for TEST-ARCHON.

Pure Python — zero external framework dependencies.
All types are Pydantic BaseModel (v2) for serialisation convenience,
but no FastAPI / HTTP concepts leak in here.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional
from datetime import datetime, timezone


# ---------------------------------------------------------------------------
# Value objects & enums
# ---------------------------------------------------------------------------

class Severity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class TestStatus(str, Enum):
    PASSED = "passed"
    FAILED = "failed"
    ERROR = "error"
    SKIPPED = "skipped"


class AgentEventType(str, Enum):
    STARTED = "started"
    PROGRESS = "progress"
    COMPLETED = "completed"
    FAILED = "failed"


# ---------------------------------------------------------------------------
# Core domain models
# ---------------------------------------------------------------------------

@dataclass
class FileDiff:
    """Represents the diff of a single file within a commit or PR."""
    path: str
    additions: int
    deletions: int
    patch: str  # raw unified-diff text — parsed locally, never sent to LLM


@dataclass
class CodeDiff:
    """Aggregated diff produced by the Git port — no LLM cost."""
    commit_sha: str
    branch: str
    base_branch: str
    files: list[FileDiff] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def changed_paths(self) -> list[str]:
        return [f.path for f in self.files]

    @property
    def total_additions(self) -> int:
        return sum(f.additions for f in self.files)

    @property
    def total_deletions(self) -> int:
        return sum(f.deletions for f in self.files)


@dataclass
class ImpactedModule:
    """A module/file identified as impacted by a diff."""
    path: str
    severity: Severity
    reason: str  # human-readable explanation (generated by LLM or AST analysis)


@dataclass
class ImpactAnalysis:
    """Result produced by the ImpactAgent."""
    diff_sha: str
    impacted_modules: list[ImpactedModule] = field(default_factory=list)
    analysis_summary: str = ""
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class CoverageGap:
    """A missing test case identified by the GeneratorAgent."""
    module_path: str
    function_name: str
    description: str
    severity: Severity = Severity.MEDIUM


@dataclass
class GeneratedTest:
    """A test case produced by the LLM via the GeneratorAgent."""
    target_module: str
    test_code: str
    language: str = "python"
    framework: str = "pytest"


@dataclass
class TestResult:
    """Outcome of running a single test via the runner port."""
    test_id: str
    test_name: str
    status: TestStatus
    duration_ms: float
    error_message: Optional[str] = None
    stdout: str = ""


@dataclass
class TestSuiteResult:
    """Aggregated result of a full test-suite run."""
    run_id: str
    results: list[TestResult] = field(default_factory=list)
    coverage_percent: float = 0.0
    ran_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def passed(self) -> int:
        return sum(1 for r in self.results if r.status == TestStatus.PASSED)

    @property
    def failed(self) -> int:
        return sum(1 for r in self.results if r.status == TestStatus.FAILED)


# ---------------------------------------------------------------------------
# Event model for bob_sessions traceability
# ---------------------------------------------------------------------------

@dataclass
class OrchestratorEvent:
    """Formal event emitted by the orchestrator and persisted to bob_sessions/."""
    session_id: str
    event_type: AgentEventType
    agent: str          # e.g. "ImpactAgent", "GeneratorAgent", "HealingAgent"
    payload: dict       # free-form serialisable dict
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
